-- Create news_credibility_analysis table for AI fake news detection results
CREATE TABLE IF NOT EXISTS `news_credibility_analysis` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `news_id` int(11) NOT NULL COMMENT 'Reference to news article',
  `credibility_score` decimal(5,2) DEFAULT '50.00' COMMENT 'Overall credibility score (0-100)',
  `trust_level` enum('very_low','low','medium','high','very_high') DEFAULT 'medium' COMMENT 'Trust level classification',
  `confidence_level` decimal(3,2) DEFAULT '0.50' COMMENT 'AI confidence in the analysis (0.00-1.00)',
  `risk_level` enum('low','medium','high','critical') DEFAULT 'medium' COMMENT 'Risk level for misinformation',
  `analysis_method` enum('ai_pattern','source_check','content_analysis','combined') DEFAULT 'combined' COMMENT 'Method used for analysis',
  `pattern_matches` json DEFAULT NULL COMMENT 'Details of pattern matches found',
  `source_analysis` json DEFAULT NULL COMMENT 'Source credibility analysis details',
  `content_analysis` json DEFAULT NULL COMMENT 'Content analysis results',
  `sentiment_analysis` json DEFAULT NULL COMMENT 'Sentiment analysis results',
  `language_analysis` json DEFAULT NULL COMMENT 'Language and tone analysis',
  `fact_check_results` json DEFAULT NULL COMMENT 'Fact checking results if available',
  `warnings` json DEFAULT NULL COMMENT 'Specific warnings generated',
  `recommendations` json DEFAULT NULL COMMENT 'Recommendations for editors/users',
  `manual_review_required` tinyint(1) DEFAULT '0' COMMENT 'Whether manual review is required',
  `review_status` enum('pending','reviewed','approved','flagged') DEFAULT 'pending' COMMENT 'Review status',
  `reviewed_by` int(11) DEFAULT NULL COMMENT 'ID of admin who reviewed',
  `review_notes` text DEFAULT NULL COMMENT 'Notes from manual review',
  `auto_flagged` tinyint(1) DEFAULT '0' COMMENT 'Whether automatically flagged as suspicious',
  `flag_reason` varchar(500) DEFAULT NULL COMMENT 'Reason for auto-flagging',
  `analysis_version` varchar(20) DEFAULT '1.0' COMMENT 'Version of analysis algorithm',
  `processing_time` decimal(8,3) DEFAULT NULL COMMENT 'Time taken for analysis in seconds',
  `analysis_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When the analysis was performed',
  `last_updated` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_news_analysis` (`news_id`),
  KEY `idx_credibility_score` (`credibility_score`),
  KEY `idx_trust_level` (`trust_level`),
  KEY `idx_risk_level` (`risk_level`),
  KEY `idx_confidence_level` (`confidence_level`),
  KEY `idx_analysis_method` (`analysis_method`),
  KEY `idx_auto_flagged` (`auto_flagged`),
  KEY `idx_review_status` (`review_status`),
  KEY `idx_manual_review_required` (`manual_review_required`),
  KEY `idx_analysis_date` (`analysis_date`),
  CONSTRAINT `fk_news_credibility_news` FOREIGN KEY (`news_id`) REFERENCES `news` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
