-- Create news table
CREATE TABLE `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `content` longtext NOT NULL,
  `excerpt` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `image_type` varchar(20) DEFAULT 'manual',
  `video_url` varchar(255) DEFAULT NULL,
  `video_path` varchar(255) DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `author_id` int(11) DEFAULT NULL,
  `featured_image` varchar(255) DEFAULT NULL,
  `status` enum('draft','published','featured','archived') DEFAULT 'draft',
  `news_type` varchar(50) DEFAULT 'manual',
  `is_breaking` tinyint(1) DEFAULT 0,
  `featured` tinyint(1) DEFAULT 0,
  `breaking_news` tinyint(1) DEFAULT 0,
  `views` int(11) DEFAULT 0,
  `likes_count` int(11) DEFAULT 0,
  `engagement_score` decimal(10,2) DEFAULT 0.00,
  `share_count` int(11) DEFAULT 0,
  `comment_count` int(11) DEFAULT 0,
  `meta_title` varchar(255) DEFAULT NULL,
  `meta_description` text DEFAULT NULL,
  `meta_keywords` varchar(255) DEFAULT NULL,
  `published_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `source_url` varchar(500) DEFAULT NULL COMMENT 'Original source URL for scraped articles',
  `source_name` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `sentiment_score` decimal(3,2) DEFAULT 0.00,
  `sentiment_label` varchar(20) DEFAULT 'neutral',
  `urgency` varchar(20) DEFAULT 'medium',
  `credibility_status` enum('PENDING','ANALYZED','REVIEWED') DEFAULT 'PENDING',
  `auto_flagged` tinyint(1) DEFAULT 0,
  `time_status` enum('new','recent','older') DEFAULT 'older',
  `company_name` varchar(255) DEFAULT NULL,
  `job_location` varchar(255) DEFAULT NULL,
  `salary` varchar(255) DEFAULT NULL,
  `last_date_to_apply` date DEFAULT NULL,
  `job_type` enum('Full-time','Part-time','Contract','Freelance','Internship') DEFAULT NULL,
  `apply_url` varchar(500) DEFAULT NULL,
  `requirements` text DEFAULT NULL,
  `is_job_posting` tinyint(1) DEFAULT 0,
  `is_channel_job` tinyint(1) DEFAULT 0 COMMENT 'Flag for channel-specific job postings',
  `channel_name` varchar(50) DEFAULT NULL COMMENT 'Channel name for specialized jobs',
  PRIMARY KEY (`id`),
  KEY `slug` (`slug`),
  KEY `category_id` (`category_id`),
  KEY `author_id` (`author_id`),
  KEY `status` (`status`),
  KEY `published_at` (`published_at`),
  KEY `featured` (`featured`),
  KEY `breaking_news` (`breaking_news`),
  KEY `news_type` (`news_type`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create news_sources table for RSS import functionality
CREATE TABLE `news_sources` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'Name of news source',
  `url` varchar(500) NOT NULL COMMENT 'Main URL of news source',
  `rss_url` varchar(500) DEFAULT NULL COMMENT 'RSS feed URL',
  `type` enum('rss','scrape') NOT NULL DEFAULT 'rss' COMMENT 'Import type',
  `category_id` int(11) DEFAULT NULL COMMENT 'Default category ID',
  `scrape_frequency` int(11) NOT NULL DEFAULT '60' COMMENT 'Scraping frequency in minutes',
  `status` enum('active','inactive') NOT NULL DEFAULT 'active' COMMENT 'Source status',
  `last_scraped` timestamp NULL DEFAULT NULL COMMENT 'Last successful scrape',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`),
  KEY `idx_last_scraped` (`last_scraped`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default RSS sources
INSERT IGNORE INTO `news_sources` (`name`, `url`, `rss_url`, `type`, `category_id`, `status`) VALUES
('BBC News', 'https://www.bbc.com/news', 'https://feeds.bbci.co.uk/news/rss.xml', 'rss', 1, 'active'),
('CNN News', 'https://www.cnn.com', 'https://rss.cnn.com/rss/edition.rss', 'rss', 1, 'active'),
('Reuters News', 'https://www.reuters.com', 'https://feeds.reuters.com/reuters/topNews', 'rss', 1, 'active'),
('Al Jazeera', 'https://www.aljazeera.com', 'https://www.aljazeera.com/xml/rss/all.xml', 'rss', 1, 'active'),
('Associated Press', 'https://apnews.com', 'https://feeds.apnews.com/rss/apf-topnews', 'rss', 1, 'active'),
('Fox News', 'https://www.foxnews.com', 'https://www.foxnews.com/about/rss/feedburner/foxnews/latest', 'rss', 1, 'active'),
('The Guardian', 'https://www.theguardian.com', 'https://www.theguardian.com/world/rss', 'rss', 1, 'active'),
('NBC News', 'https://www.nbcnews.com', 'https://www.nbcnews.com/id/3032091/device/rss/rss.xml', 'rss', 1, 'active'),
('CBS News', 'https://www.cbsnews.com', 'https://www.cbsnews.com/rss/live/rss.rss', 'rss', 1, 'active'),
('NPR News', 'https://www.npr.org', 'https://feeds.npr.org/1001/rss.xml', 'rss', 1, 'active');
