-- Create users table
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('admin','editor','reporter') DEFAULT 'reporter',
  `department` enum('editorial','reporting','technical','management','marketing','multimedia') DEFAULT NULL,
  `specialization` varchar(100) DEFAULT NULL,
  `experience_level` enum('junior','intermediate','senior','expert','lead') DEFAULT 'junior',
  `skills` text DEFAULT NULL,
  `social_links` text DEFAULT NULL,
  `status` enum('active','blocked') DEFAULT 'active',
  `bio` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_login` datetime DEFAULT NULL,
  `login_count` int(11) DEFAULT 0,
  `profile_views` int(11) DEFAULT 0,
  `articles_published` int(11) DEFAULT 0,
  `is_featured` tinyint(1) DEFAULT 0,
  `verification_status` enum('unverified','verified','premium') DEFAULT 'unverified',
  `preferred_language` varchar(10) DEFAULT 'en',
  `timezone` varchar(50) DEFAULT 'Asia/Karachi',
  `notification_preferences` text DEFAULT NULL,
  `working_hours` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_users_email` (`email`),
  KEY `idx_role_status` (`role`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
