-- Create news_credibility_analysis table matching the PHP code requirements
CREATE TABLE IF NOT EXISTS `news_credibility_analysis` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `news_id` int(11) NOT NULL COMMENT 'Reference to news article',
  `analysis_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When the analysis was performed',
  `credibility_score` decimal(5,2) DEFAULT '50.00' COMMENT 'Overall credibility score (0-100)',
  `confidence_level` decimal(3,2) DEFAULT '0.50' COMMENT 'AI confidence in the analysis (0.00-1.00)',
  `title_credibility` decimal(5,2) DEFAULT '50.00' COMMENT 'Title credibility score (0-100)',
  `content_credibility` decimal(5,2) DEFAULT '50.00' COMMENT 'Content credibility score (0-100)',
  `source_credibility` decimal(5,2) DEFAULT '50.00' COMMENT 'Source credibility score (0-100)',
  `factual_accuracy` decimal(5,2) DEFAULT '50.00' COMMENT 'Factual accuracy score (0-100)',
  `sensationalism_score` decimal(5,2) DEFAULT '0.00' COMMENT 'Sensationalism score (0-100)',
  `emotional_manipulation` decimal(5,2) DEFAULT '0.00' COMMENT 'Emotional manipulation score (0-100)',
  `clickbait_score` decimal(5,2) DEFAULT '0.00' COMMENT 'Clickbait score (0-100)',
  `propaganda_indicators` decimal(5,2) DEFAULT '0.00' COMMENT 'Propaganda indicators score (0-100)',
  `grammar_score` decimal(5,2) DEFAULT '50.00' COMMENT 'Grammar quality score (0-100)',
  `readability_score` decimal(5,2) DEFAULT '50.00' COMMENT 'Readability score (0-100)',
  `factual_density` decimal(5,2) DEFAULT '50.00' COMMENT 'Factual density score (0-100)',
  `source_verified` tinyint(1) DEFAULT '0' COMMENT 'Whether source is verified',
  `source_reputation_score` decimal(5,2) DEFAULT '50.00' COMMENT 'Source reputation score (0-100)',
  `cross_reference_count` int(11) DEFAULT '0' COMMENT 'Number of cross-references found',
  `analysis_method` varchar(50) DEFAULT 'AI_MULTIMODEL' COMMENT 'Method used for analysis',
  `processing_time_ms` int(11) DEFAULT '0' COMMENT 'Time taken for analysis in milliseconds',
  `ai_model_version` varchar(20) DEFAULT 'v2.1' COMMENT 'Version of AI model',
  `risk_level` enum('low','medium','high','critical') DEFAULT 'medium' COMMENT 'Risk level for misinformation',
  `content_category` varchar(50) DEFAULT 'general' COMMENT 'Content category',
  `requires_review` tinyint(1) DEFAULT '0' COMMENT 'Whether manual review is required',
  `auto_flagged` tinyint(1) DEFAULT '0' COMMENT 'Whether automatically flagged as suspicious',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_news_analysis` (`news_id`),
  KEY `idx_credibility_score` (`credibility_score`),
  KEY `idx_risk_level` (`risk_level`),
  KEY `idx_auto_flagged` (`auto_flagged`),
  KEY `idx_analysis_date` (`analysis_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
